- name: Store custom quarto versions in extra variable
  ansible.builtin.set_fact:
    custom_quarto_versions: "{{ quarto_versions | reject('search', 'release') | reject('search', 'prerelease') | list }}"
  when: quarto_versions | reject('search', 'release') | reject('search', 'prerelease') | list | length > 0

- name: Get Quarto latest release from GitHub
  ansible.builtin.uri:
    url: https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest
    return_content: yes
    headers:
      Accept: "application/vnd.github.v3+json"
  register: latest_release
  when: "'release' in quarto_versions"

- name: Infer latest release Quarto version
  ansible.builtin.set_fact:
    quarto_release_version: "{{ latest_release.json.tag_name | replace('v', '') }}"
  when: "'release' in quarto_versions"

- name: Get Quarto releases from GitHub
  ansible.builtin.uri:
    url: https://api.github.com/repos/quarto-dev/quarto-cli/releases
    return_content: yes
    headers:
      Accept: "application/vnd.github.v3+json"
  register: all_releases
  when: "'pre-release' in quarto_versions"

- name: Infer latest pre-release Quarto version
  ansible.builtin.set_fact:
    quarto_prerelease_version: "{{ (all_releases.json | selectattr('prerelease', 'equalto', true) | sort(attribute='created_at', reverse=true) | first).tag_name | replace('v', '') }}"
  when: "'pre-release' in quarto_versions"

- name: Combine quarto versions into a list
  ansible.builtin.set_fact:
    quarto_versions: "{{ [quarto_release_version, quarto_prerelease_version] + (custom_quarto_versions | default([])) }}"

- name: Define environment facts
  ansible.builtin.set_fact:
    arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Download quarto binary
  ansible.builtin.get_url:
    url: "https://github.com/quarto-dev/quarto-cli/releases/download/v{{ item }}/quarto-{{ item }}-linux-{{ arch }}.tar.gz"
    dest: "/tmp/quarto-{{ item }}.tar.gz"
  loop: "{{ quarto_versions }}"

- name: Ensure quarto directory exists
  ansible.builtin.file:
    path: "{{ quarto_dest_dir }}"
    state: directory
    mode: 0755

- name: Extract quarto binary
  ansible.builtin.unarchive:
    src: "/tmp/quarto-{{ item }}.tar.gz"
    dest: "{{ quarto_dest_dir }}"
    remote_src: true
  loop: "{{ quarto_versions }}"

- name: Cleanup downloaded assets
  ansible.builtin.file:
    path: "/tmp/quarto-{{ item }}.tar.gz"
    state: absent
  loop: "{{ quarto_versions }}"

- name: Add quarto to PATH
  when: quarto_add_to_path | bool
  ansible.builtin.blockinfile:
    path: /etc/profile.d/quarto.sh
    block: |
      export PATH={{ quarto_dest_dir }}/quarto-{{ quarto_versions | first }}/bin:$PATH
    create: true
    state: present
    marker: "# {mark} ANSIBLE MANAGED BLOCK quarto"
