- name: Encrypt OIDC secret
  become: true
  ansible.builtin.shell: |
    echo "{{ workbench_server_oidc_client_secret }}" | rstudio-server encrypt-password
  register: encrypted_oidc_secret

- name: Set OIDC secret
  when: workbench_server_oidc_client_secret is defined
  ansible.builtin.lineinfile:
    path: /etc/rstudio/openid-client-secret
    regexp: client-secret
    line: client-secret={{ encrypted_oidc_secret.stdout }}
