- name: Encrypt Postgresql Database Password
  ansible.builtin.shell: |
    echo "{{ workbench_database_password }}" | rstudio-server encrypt-password
  register: encrypted_postgresql_password

- name: Set Postgresql Password
  when: workbench_database_password is defined
  ansible.builtin.lineinfile:
    path: /etc/rstudio/database.conf
    regexp: password
    line: password={{ encrypted_postgresql_password.stdout }}
  no_log: true
