# handlers file for workbench

- name: Encrypt OIDC client secret
  when: workbench_server_oidc_client_secret is defined
  ansible.builtin.include_tasks: 01_secret_oidc.yaml

- name: Restart rstudio-server service
  ansible.builtin.service:
    name: rstudio-server
    state: restarted
    enabled: true
    daemon_reload: true
  ignore_errors: true

- name: Restart rstudio-launcher service
  ansible.builtin.service:
    name: rstudio-launcher
    state: restarted
    enabled: true
    daemon_reload: true
  ignore_errors: true
