---
# defaults file for python

# this always installs the latest version of the respective minor
# string notation is important as otherwise trailing zeros are cut
python_python_versions:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

python_update_versions: true
python_remove_versions: true
