### REQUIRED
namespace: devxy

name: posit

version: 1.0.1

readme: README.md

authors:
  - Patrick Schratz <mail@devxy.io>

description: Collection of roles to install Posit applications

license:
  - AGPL-3.0-or-later

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags: ["tools"]

dependencies: {}

repository: https://gitlab.com/devxy/ansible/posit

# The URL to the homepage of the collection/project
homepage: https://www.devxy.io

# The URL to the collection issue tracker
issues: https://gitlab.com/devxy/ansible/posit/issues

# A list of file glob-like patterns used to filter any files or directories that should not be included in the build
# artifact. A pattern is matched from the relative path of the file or directory of the collection directory. This
# uses 'fnmatch' to match the files or directories. Some directories and files like 'galaxy.yml', '*.pyc', '*.retry',
# and '.git' are always filtered. Mutually exclusive with 'manifest'
# build_ignore:

# A dict controlling use of manifest directives used in building the collection artifact. The key 'directives' is a
# list of MANIFEST.in style
# L(directives,https://packaging.python.org/en/latest/guides/using-manifest-in/#manifest-in-commands). The key
# 'omit_default_directives' is a boolean that controls whether the default directives are used. Mutually exclusive
# with 'build_ignore'
manifest:
  directives:
    - recursive-exclude ansible_collections/ **
    - recursive-exclude readme/ **
    - recursive-exclude ansibledoctor/ **
    - recursive-exclude .woodpecker/ **
    - recursive-exclude .gitsv/ **
    - global-exclude *.tar.gz
    - global-exclude *.cfg
    - global-exclude *.ini
    - global-exclude *.mjs
