collections:
  - name: devxy.data_science_core
    version: 1.0.5
  - name: community.crypto
    version: 2.26.5
roles:
  - name: nginxinc.nginx
    version: 0.25.0
  - name: nginxinc.nginx_config
    version: 0.7.1
  - name: geerlingguy.certbot
    version: 5.4.1
