- name: Enable EPEL repo (9)
  changed_when: false
  when: ansible_facts['os_family'] == 'RedHat' and  ansible_distribution_major_version | int == 9
  ansible.builtin.command: dnf config-manager --set-enabled crb

- name: Enable EPEL repo (8)
  changed_when: false
  when: ansible_facts['os_family'] == 'RedHat' and ansible_distribution_major_version|int == 8
  ansible.builtin.shell: |
    dnf install -y yum-utils
    dnf config-manager --set-enabled powertools

- name: Install EPEL
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.dnf:
    name:
      - epel-release
      - dnf-plugins-core

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install required system libraries
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{
    (ansible_facts['os_family'] == 'Debian') | ternary(r_package_syslibs_debian,
    (ansible_facts['os_family'] == 'RedHat') | ternary(r_package_syslibs_redhat,
    (ansible_facts['os_family'] == 'Suse') | ternary(r_package_syslibs_suse, [])))
    }}"
  when: "item not in ansible_facts.packages"
