- name: Apply Posit Workbench configuration (/etc/rstudio)
  ansible.builtin.template:
    src: "{{ item.file }}.j2"
    dest: "/etc/rstudio/{{ item.file }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { file: "database.conf", mode: "0600" }
