- name: Install python3 development package
  ansible.builtin.package:
    name: "{{ 'python3-dev' if ansible_facts['os_family'] == 'Debian' else 'python3-devel' }}"
    state: present

- name: Install JupyterLab and JupyterNotebook
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - jupyterlab{{ workbench_jupyterlabs_version }}
    - notebook{{ workbench_jupyternotebook_version }}
    - pwb_jupyterlab{{ workbench_posit_jupyterlab_extension_version}}
  notify: Restart rstudio-server service
