---
# tasks file for workbench

# - name: Import 01_syslibs.yaml
#   ansible.builtin.import_tasks: 01_syslibs.yaml

# - name: Import 02_r.yaml
#   ansible.builtin.import_tasks: 02_r.yaml

# - name: Import 02_dirs.yaml
#   ansible.builtin.import_tasks: 02_dirs.yaml

# - name: Import 03_install.yaml
#   ansible.builtin.import_tasks: 03_install.yaml

# - name: Import jupyter.yaml
#   ansible.builtin.import_tasks: jupyter.yaml

# - name: Import startup.yaml
#   ansible.builtin.import_tasks: startup.yaml

- name: Import renv.yaml
  ansible.builtin.import_tasks: renv.yaml

- name: Import 04_config.yaml
  ansible.builtin.import_tasks: 04_config.yaml

# - name: Import secrets.yaml
#   ansible.builtin.import_tasks: secrets.yaml

# - name: Import fonts.yaml
#   ansible.builtin.import_tasks: fonts.yaml
