---
# tasks file for workbench

# - name: Import 01_syslibs.yaml
#   ansible.builtin.import_tasks: 01_syslibs.yaml

# - name: Import 02_dirs.yaml
#   ansible.builtin.import_tasks: 02_dirs.yaml

- name: Import 03_install.yaml
  ansible.builtin.import_tasks: 03_install.yaml
# - name: Import 04_renv.yaml
#   ansible.builtin.import_tasks: 04_renv.yaml

# - name: Import 05_fonts.yaml
#   ansible.builtin.import_tasks: 05_fonts.yaml

# - name: Import 06_secrets.yaml
#   ansible.builtin.import_tasks: 06_secrets.yaml

# - name: Import 07_startup.yaml
#   ansible.builtin.import_tasks: 07_startup.yaml

- name: Import 08_config.yaml
  ansible.builtin.import_tasks: 08_config.yaml
