# - name: Set Posit License
#   when: workbench_file_license is defined
#   ansible.builtin.copy:
#     content: "{{ workbench_file_license }}"
#     dest: "/var/lib/rstudio-server/license.lic"
#     owner: root
#     group: root
#     mode: "0600"
#   notify: Restart rstudio-server service

# - name: Create Launcher Key Pair
#   ansible.builtin.openssl_privatekey:
#     path: "/etc/rstudio/launcher.pem"
#     type: RSA
#     size: 4096
#     mode: 0600
#   register: launcher_key

# - name: Create Launcher Public Key
#   ansible.builtin.openssl_publickey:
#     privatekey_path: "/etc/rstudio/launcher.pem"
#     path: "/etc/rstudio/launcher.pub"

- name: Create Launcher SSL Private Key
  ansible.builtin.openssl_privatekey:
    path: "/var/lib/rstudio-launcher/localhost.key"
    type: RSA
    size: 4096
    mode: 0600
    owner: "{{ workbench_server_user }}"
    group: "{{ workbench_server_user }}"

- name: Create a CSR with the common name localhost
  ansible.builtin.openssl_csr:
    path: "/tmp/localhost.csr"
    privatekey_path: "/var/lib/rstudio-launcher/localhost.key"
    common_name: "localhost"

- name: Create localhost self-signed cert to enable launcher SSL
  ansible.builtin.openssl_certificate:
    path: "/var/lib/rstudio-launcher/localhost.crt"
    privatekey_path: "/var/lib/rstudio-launcher/localhost.key"
    csr_path: "/tmp/localhost.csr"
    mode: 0600
    provider: selfsigned
    owner: "{{ workbench_server_user }}"
    group: "{{ workbench_server_user }}"

- name: Create secure-cookie-key
  ansible.builtin.copy:
    content: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"
    dest: "/etc/rstudio/secure-cookie-key"
    owner: root
    group: root
    mode: "0600"
  notify: Restart rstudio-server service
