- name: Make sure /opt/R exists
  ansible.builtin.file:
    path: /opt/R
    state: directory

- name: List installed R versions under /opt/R
  ansible.builtin.stat:
    path: "/opt/R/{{ item }}/bin/R"
  loop: "{{ r_r_versions }}"
  register: r_installed

- name: Execute RedHat tasks
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.import_tasks: redhat.yaml

- name: Execute Ubuntu tasks
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.import_tasks: ubuntu.yaml

- name: Create Renviron and Rprofile
  ansible.builtin.blockinfile:
    path: "/opt/R/{{ item }}/lib/R/etc/Renviron"
    block: |
      R_ENVIRON='/etc/Renviron.site'
      R_PROFILE='/etc/Rprofile.site'
      QUARTO_R=/opt/R/{{ item }}/lib/R/bin/R
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  loop: "{{ r_r_versions }}"

- name: Configure R-version specific Renviron
  ansible.builtin.blockinfile:
    path: "/opt/R/{{ item }}/lib/R/etc/Renviron"
    block: |
      R_ENVIRON='/etc/Renviron.site'
      R_PROFILE='/etc/Rprofile.site'
      QUARTO_R=/opt/R/{{ item }}/lib/R/bin/R
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  loop: "{{ r_r_versions }}"
