# to be able to install R-core
- name: Ensure R-core deps are installed (1)
  ansible.builtin.dnf:
    name: epel-release
    state: present

# for flexiblas-devel
- name: Enable appropriate repository for RedHat 8 or 9
  community.general.dnf_config_manager:
    name: "{{ 'crb' if ansible_distribution_major_version | int == 9 else 'powertools' }}"
    state: enabled
  when: ansible_distribution_major_version | int in [8, 9]

- name: Ensure R-core deps are installed (2)
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.dnf:
    name: "{{ 'flexiblas-devel' if ansible_distribution_major_version | int == 9 else 'openblas-devel' }}"
    update_cache: true
    state: present

# otherwise /usr/lib/rstudio-server/bin/rsession will fail to find libR
- name: Ensure R-core is installed
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.dnf:
    name: R
    state: present

- name: Check if /opt/R is empty
  ansible.builtin.find:
    paths: /opt/R
    file_type: directory
    patterns: "[0-9]\\.[0-9]\\.[0-9]"
  register: any_r_installed

- name: List all installed R versions
  when: r_remove_old_r_versions | bool and any_r_installed.matched | int != 0
  changed_when: false
  ansible.builtin.shell: dnf list installed | grep R-[0-9] | awk -F- '{print $2}' | awk -F. '{print $1"."$2"."$3}'
  register: r_installed_list

- name: Set variable r_installed_list if no R versions are installed
  when: r_remove_old_r_versions | bool and not any_r_installed.matched
  ansible.builtin.set_fact:
    r_installed_list: { stdout_lines: [] }

- name: Create diff between lists
  when: any_r_installed.matched | int != 0
  ansible.builtin.set_fact:
    unwanted_r_versions: "{{ r_installed_list.stdout_lines | difference(r_versions) }}"

- name: Remove deprecated/old R versions
  when: r_remove_old_r_versions | bool and any_r_installed.matched | int != 0
  ansible.builtin.dnf:
    name: "R-{{ item }}.{{ ansible_architecture }}"
    state: absent
  loop: "{{ unwanted_r_versions }}"

- name: Download R binary (arm64)
  when: ansible_architecture == 'aarch64' and not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
  ansible.builtin.get_url:
    url: "https://devxy-r-builds.s3.eu-central-2.amazonaws.com/el{{ ansible_distribution_major_version }}/R-{{ item }}-1-1.aarch64.rpm"
    dest: "/tmp/R-{{ item }}.rpm"
    force: true
    mode: "0644"
  loop: "{{ r_versions }}"

- name: Set Posit OS identifier for download
  ansible.builtin.set_fact:
    posit_os_identifier: "{{ 'centos' if ansible_distribution_major_version | int == 8 else 'rhel' if ansible_distribution_major_version | int == 9 else 'unsupported' }}"

- name: Download R binary
  when: ansible_architecture == 'x86_64' and not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
  ansible.builtin.get_url:
    url: "https://cdn.posit.co/r/{{ posit_os_identifier }}-{{ ansible_distribution_major_version }}/pkgs/R-{{ item }}-1-1.x86_64.rpm"
    dest: "/tmp/R-{{ item }}.rpm"
    mode: "0644"
  loop: "{{ r_versions }}"

- name: Uninstall existing R binaries
  when: not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
  ansible.builtin.dnf:
    name: "r-{{ item }}"
    state: absent
  loop: "{{ r_versions }}"

- name: Install R binary
  when: not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
  ansible.builtin.dnf:
    name: "/tmp/R-{{ item }}.rpm"
    state: present
    disable_gpg_check: true
  loop: "{{ r_versions }}"

- name: Cleanup downloaded assets
  when: not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
  ansible.builtin.file:
    path: "/tmp/R-{{ item }}.rpm"
    state: absent
  loop: "{{ r_versions }}"

- name: Configure /etc/Rprofile.site (default)
  when: r_r_custom_repos is undefined
  ansible.builtin.blockinfile:
    create: true
    path: /etc/Rprofile.site
    block: |
      options(install.packages.check.source = 'no',
        repos = 'c(CRAN = "https://packagemanager.posit.co/cran/__linux__/{{ posit_os_identifier{{ ansible_distribution_major_version }}/latest")')
