- name: Gather package facts
  ansible.builtin.package_facts:
    manager: apt

- name: Ensure R-core deps are installed (2)
  when: "item not in ansible_facts.packages"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - g++
    - gdebi
    - gdebi-core
    - gfortran
    - libblas-dev
    - libbz2-dev
    - libicu-dev
    - liblapack-dev
    - liblzma-dev
    - libopenblas-dev
    - libpaper-utils
    - libpcre2-dev
    - libpcre3-dev
    - libtcl8.6
    - libtk8.6
    - libxt6
    - unzip
    - zip
    - zlib1g-dev

- name: Check if /opt/R is empty
  ansible.builtin.find:
    paths: /opt/R
    file_type: directory
    patterns: "[0-9]\\.[0-9]\\.[0-9]"
  register: any_r_installed

- name: List all installed R versions
  when: r_remove_old_r_versions | bool and any_r_installed.matched | int != 0
  changed_when: false
  ansible.builtin.shell: ls -d /opt/R/*/ | xargs -n 1 basename
  register: r_installed_list

- name: Set variable r_installed_list if no R versions are installed
  when: r_remove_old_r_versions | bool and not any_r_installed.matched
  ansible.builtin.set_fact:
    r_installed_list: { stdout_lines: [] }

- name: Create diff between lists
  when: any_r_installed.matched | int != 0
  ansible.builtin.set_fact:
    unwanted_r_r_versions: "{{ r_installed_list.stdout_lines | difference(r_r_versions) }}"

- name: Remove deprecated/old R versions
  when: r_remove_old_r_versions | bool and any_r_installed.matched | int != 0
  ansible.builtin.file:
    path: "/opt/R/{{ item }}"
    state: absent
  loop: "{{ unwanted_r_versions }}"

- name: Set OS identifier for download
  ansible.builtin.set_fact:
    os_identifier: "{{ '2404' if ansible_distribution_version == '24.04' else '2204' if ansible_distribution_version == '22.04' else '2004' if ansible_distribution_version == '20.04' }}"

- name: Download R binary (arm64)
  when: ansible_architecture == 'aarch64' and not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
  ansible.builtin.get_url:
    url: "https://devxy-r-builds.s3.eu-central-003.backblazeb2.com/{{ os_identifier }}/r-{{ item }}_1_arm64.deb"
    dest: "/tmp/R-{{ item }}.deb"
    force: true
    mode: "0644"
  loop: "{{ r_r_versions }}"

- name: Download R binary
  when: ansible_architecture == 'x86_64' and not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
  ansible.builtin.get_url:
    url: "https://cdn.posit.co/r/ubuntu-{{ os_identifier }}/pkgs/r-{{ item }}_1_amd64.deb"
    dest: "/tmp/R-{{ item }}.deb"
    mode: "0644"
  loop: "{{ r_r_versions }}"

- name: Install R binary
  when: not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
  ansible.builtin.apt:
    deb: "/tmp/R-{{ item }}.deb"
    state: present
  loop: "{{ r_r_versions }}"

- name: Cleanup downloaded assets
  when: not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
  ansible.builtin.file:
    path: "/tmp/R-{{ item }}.deb"
    state: absent
  loop: "{{ r_r_versions }}"
