# @var workbench_syslibs_manage_repos:type: boolean
# @var workbench_syslibs_manage_repos:description: Manage system repositories (EPEL, CRB/PowerTools). Set to false to skip repo setup.
workbench_syslibs_manage_repos: true
