r_package_syslibs_debian:
  - libbz2-dev
  - libcurl4-openssl-dev
  - libgdal-dev
  - libgeos-dev
  - libgmp-dev
  - libicu-dev
  - liblzma-dev
  - libmagick++-dev
  - libmpfr-dev
  - libpcre2-dev
  - libpoppler-cpp-dev
  - libproj-dev
  - libssl-dev
  - libudunits2-dev
  - libxml2-dev
  - libz-dev
  - unzip

r_package_syslibs_redhat:
  - cairo
  - fontconfig-devel
  - freetds-devel
  - freetype-devel
  - fribidi
  - gdal
  - gdal-devel
  - gdal-libs
  - geos-devel
  - git
  - glpk
  - glpk-devel
  - harfbuzz
  - ImageMagick-c++
  - ImageMagick-c++-devel
  - ImageMagick-libs
  - java-17-openjdk
  - java-17-openjdk-devel
  - jq
  - jq-devel
  - libaio
  - libcurl-devel
  - libgit2-devel
  - libicu-devel
  - libiodbc
  - libjpeg-turbo-devel
  - libpng-devel
  - libpq-devel
  - libsecret
  - libsodium-devel
  - libssh-devel
  - libtiff-devel
  - libuuid-devel
  - libxml2-devel
  - libxslt-devel
  - mesa-libGLU
  - mpfr
  - netcdf-devel
  - openblas
  - openssl-devel
  - proj-devel
  - qpdf-libs
  - readline
  - sqlite-devel
  - tzdata
  - udunits2-devel
  - unixODBC-devel
  - unzip
  - zlib-devel
