- name: Create directory for Posit DB Drivers
  ansible.builtin.file:
    path: "/opt/rstudio-drivers-{{ db_drivers_version }}"
    state: directory
    mode: "0775"

- name: Execute RedHat tasks
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.import_tasks: redhat.yaml

- name: Execute Ubuntu tasks
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.import_tasks: ubuntu.yaml

- name: Check if directory is empty
  ansible.builtin.find:
    paths: "/opt/rstudio-drivers-{{ db_drivers_version }}"
  register: dir_content

- name: Download Posit DB Drivers
  when: dir_content.files | length == 0
  ansible.builtin.get_url:
    url: "https://cdn.rstudio.com/drivers/7C152C12/installer/rstudio-drivers-{{ db_drivers_version }}.tar"
    dest: "/tmp/rstudio-drivers-{{ db_drivers_version }}.tar"
    mode: "0755"

- name: Extract Posit DB Drivers
  when: dir_content.files | length == 0
  ansible.builtin.unarchive:
    src: "/tmp/rstudio-drivers-{{ db_drivers_version }}.tar"
    dest: "/opt"
    remote_src: true

- name: Cleanup Posit DB Drivers tarball
  when: dir_content.files | length == 0
  ansible.builtin.file:
    path: "/tmp/rstudio-drivers-{{ db_drivers_version }}.tar"
    state: absent

- name: Check if odbcinst.ini exists
  ansible.builtin.stat:
    path: /etc/odbcinst.ini
  register: odbcinst_ini_stat

- name: Backup existing odbcinst.ini if it exists
  ansible.builtin.copy:
    src: /etc/odbcinst.ini
    dest: /tmp/odbcinst.ini.bak
    mode: "0644"
    remote_src: true
  when: odbcinst_ini_stat.stat.exists

- name: Create odbcinst.ini from template
  ansible.builtin.copy:
    src: "/opt/rstudio-drivers-{{ db_drivers_version }}/odbcinst.ini.sample"
    dest: /etc/odbcinst.ini
    remote_src: true
    mode: "0644"

- name: Print message about backup
  ansible.builtin.debug:
    msg: "Backup of /etc/odbcinst.ini created at /tmp/odbcinst.ini.bak"
  when: odbcinst_ini_stat.stat.exists

- name: Append additional odbcinst.ini entries
  when: extra_odbcinst_entries != ""
  ansible.builtin.blockinfile:
    path: /etc/odbcinst.ini
    block: |
      "{{ extra_odbcinst_entries }}"

- name: Insert professional driver version into file paths in odbcinst.ini
  ansible.builtin.replace:
    path: /etc/odbcinst.ini
    regexp: '(/rstudio-drivers/)'
    replace: '/rstudio-drivers-{{ db_drivers_version }}/'

- name: Write odbc.ini
  when: odbc_ini != ""
  ansible.builtin.blockinfile:
    path: /etc/odbc.ini
    block: |
      {{ odbc_ini }}
