- name: Create directory for Posit DB Drivers
  ansible.builtin.file:
    path: "{{ db_drivers_install_dir }}/rstudio-drivers-{{ db_drivers_version }}"
    state: directory
    mode: "0775"

- name: Execute RedHat tasks
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.import_tasks: redhat.yaml

- name: Execute Ubuntu tasks
  when: ansible_facts['distribution'] == 'Ubuntu'
  ansible.builtin.import_tasks: ubuntu.yaml

# Download from Artifactory when enabled
- name: Import 01_download_artifactory.yaml
  when: db_drivers_artifactory_enabled | bool
  ansible.builtin.import_tasks: 01_download_artifactory.yaml

# Download from default source when Artifactory is disabled
- name: Import 01_download_default.yaml
  when: not db_drivers_artifactory_enabled | bool
  ansible.builtin.import_tasks: 01_download_default.yaml

- name: Check if odbcinst.ini exists
  ansible.builtin.stat:
    path: /etc/odbcinst.ini
  register: odbcinst_ini_stat

- name: Backup existing odbcinst.ini if it exists
  ansible.builtin.copy:
    src: /etc/odbcinst.ini
    dest: /tmp/odbcinst.ini.bak
    mode: "0644"
    remote_src: true
  when: odbcinst_ini_stat.stat.exists

- name: Create odbcinst.ini from template
  ansible.builtin.copy:
    src: "{{ db_drivers_install_dir }}/rstudio-drivers-{{ db_drivers_version }}/odbcinst.ini.sample"
    dest: /etc/odbcinst.ini
    remote_src: true
    mode: "0644"
  when: not ansible_check_mode

- name: Print message about backup
  ansible.builtin.debug:
    msg: "Backup of /etc/odbcinst.ini created at /tmp/odbcinst.ini.bak"
  when: odbcinst_ini_stat.stat.exists

- name: Append additional odbcinst.ini entries
  when: extra_odbcinst_entries != ""
  ansible.builtin.blockinfile:
    path: /etc/odbcinst.ini
    block: |
      "{{ extra_odbcinst_entries }}"

- name: Update driver paths in odbcinst.ini to match install directory and version
  ansible.builtin.replace:
    path: /etc/odbcinst.ini
    regexp: "/opt/rstudio-drivers/"
    replace: "{{ db_drivers_install_dir }}/rstudio-drivers-{{ db_drivers_version }}/"

- name: Write odbc.ini
  when: odbc_ini != ""
  ansible.builtin.blockinfile:
    path: /etc/odbc.ini
    block: |
      {{ odbc_ini }}

# Oracle Instant Client
- name: Import Oracle Instant Client tasks
  when: db_drivers_oracle_enabled | bool
  ansible.builtin.import_tasks: 02_oracle_instantclient.yaml
