template:
  name: readme
  src: local>../../ansibledoctor/templates
  options:
    tabulate_vars: true

logging:
  # Possible options: debug|info|warning| error|critical
  level: "info"

renderer:
  include_header: HEADER.md
  force_overwrite: true
