---
# defaults file for workbench

### GENERAL

r_package_syslibs_debian:
  - libcurl4-openssl-dev
  - libssl-dev
  - libxml2-dev
  - libz-dev
  - libbz2-dev
  - libpcre2-dev
  - liblzma-dev
  - libicu-dev
  - libgmp-dev
  - libmpfr-dev
  - libudunits2-dev
  - libgdal-dev
  - libgeos-dev
  - libproj-dev
  - libmagick++-dev
  - libpoppler-cpp-dev

### R

# removes all R versions that are not in the r_versions list
remove_old_r_versions: true

r_versions:
  - 4.0.5
  - 4.1.3
  - 4.2.3
  - 4.3.3

### Workbench

workbench_version:
  "2024.04.1-748.pro2"

# database.conf
workbench_database_provider: sqlite
workbench_database_directory: /var/lib/rstudio-server
workbench_database_host: localhost
workbench_database_database: workbenchdb
workbench_database_username: workbench_db_user
workbench_database_password: workbench_db_password
workbench_database_port: 5432
workbench_database_connection_timeout_seconds: 10
workbench_database_connection_uri: ""
