- name: Ensure dnf config-manager is installed
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.dnf:
    name:
      - yum-utils

- name: Ensure python-apt is installed
  when: ansible_facts['os_family'] == 'Debian'
  ansible.builtin.apt:
    name:
      - python-apt

- name: Enable appropriate repository for RedHat 8 or 9
  community.general.dnf_config_manager:
    name: "{{ 'crb' if ansible_distribution_major_version | int == 9 else 'powertools' }}"
    state: enabled
  when: ansible_distribution_major_version | int in [8, 9] and ansible_facts['os_family'] == 'RedHat'

- name: Install EPEL
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.dnf:
    name:
      - epel-release
      - dnf-plugins-core

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install required system libraries
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{
    (ansible_facts['os_family'] == 'Debian') | ternary(r_package_syslibs_debian,
    (ansible_facts['os_family'] == 'RedHat') | ternary(r_package_syslibs_redhat,
    (ansible_facts['os_family'] == 'Suse') | ternary(r_package_syslibs_suse, [])))
    }}"
  when: "item not in ansible_facts.packages"
