- name: Ensure dnf config-manager is installed
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.dnf:
    name:
      - yum-utils

- name: Ensure python3-apt is installed
  when: ansible_facts['os_family'] == 'Debian'
  ansible.builtin.apt:
    name:
      - python3-apt

- name: Enable appropriate repository for RedHat 8 or 9
  community.general.dnf_config_manager:
    name: "{{ 'crb' if ansible_facts['distribution_major_version'] | int == 9 else 'powertools' }}"
    state: enabled
  when:
    - workbench_syslibs_manage_repos | default(true)
    - ansible_distribution_major_version | int in [8, 9]
    - ansible_facts['os_family'] == 'RedHat'

- name: Install EPEL
  when:
    - workbench_syslibs_manage_repos | default(true)
    - ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.dnf:
    name:
      - epel-release
      - dnf-plugins-core
