- name: Configure renv
  block:
    - name: Check if Renviron.site exists
      ansible.builtin.stat:
        path: /etc/Renviron.site
      register: renviron_site

    - name: Create Renviron.site if it does not exist
      ansible.builtin.command:
        cmd: touch /etc/Renviron.site
      when: not renviron_site.stat.exists
      changed_when: false

    - name: Ensure /opt/R/renv exists
      ansible.builtin.file:
        path: /opt/R/renv
        state: directory
        owner: root
        group: root
        mode: "0777"

    - name: Insert renv env vars
      ansible.builtin.blockinfile:
        path: /etc/Renviron.site
        block: |
          RENV_PATHS_ROOT=/opt/R/renv
          RENV_PATHS_CACHE=/opt/R/renv/cache
          RENV_PATHS_BINARY=/opt/R/renv/binary
          RENV_PATHS_LOCAL=/opt/R/renv/local
          RENV_PATHS_SOURCE=/opt/R/renv/source
          RENV_CONFIG_AUTO_SNAPSHOT=false
          RENV_CONFIG_INSTALL_SHORTCUTS=false
          RENV_PATHS_PREFIX_AUTO=false
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      notify: Restart rstudio-server service
