- name: Configure fonts
  when: workbench_fonts_install_custom_fonts | bool
  block:
    - name: Download JetBrains Mono font
      ansible.builtin.get_url:
        url: "https://github.com/JetBrains/JetBrainsMono/releases/download/v{{ workbench_fonts_jetbrains_mono_version }}/JetBrainsMono-{{ workbench_fonts_jetbrains_mono_version }}.zip"
        dest: "/tmp/JetBrainsMono-{{ workbench_fonts_jetbrains_mono_version }}.zip"
        mode: "0775"

    - name: Unzip JetBrains Mono font
      ansible.builtin.unarchive:
        src: "/tmp/JetBrainsMono-{{ workbench_fonts_jetbrains_mono_version }}.zip"
        dest: "/tmp/"
        remote_src: true
        creates: "/tmp/fonts"

    - name: Create directories for JetBrains Mono font
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: "{{ workbench_server_server_user }}"
        group: "{{ workbench_server_server_user }}"
      loop:
        - /etc/rstudio/fonts/JetBrainsMono/300/italic
        - /etc/rstudio/fonts/JetBrainsMono/400/italic
        - /etc/rstudio/fonts/JetBrainsMono/700/italic

    - name: Move files into place
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
        remote_src: true
      loop:
        - src: "/tmp/fonts/ttf/JetBrainsMono-Light.ttf"
          dest: "/etc/rstudio/fonts/JetBrainsMono/300/"
        - src: "/tmp/fonts/ttf/JetBrainsMono-Medium.ttf"
          dest: "/etc/rstudio/fonts/JetBrainsMono/400/"
        - src: "/tmp/fonts/ttf/JetBrainsMono-Bold.ttf"
          dest: "/etc/rstudio/fonts/JetBrainsMono/700/"
        - src: "/tmp/fonts/ttf/JetBrainsMono-LightItalic.ttf"
          dest: "/etc/rstudio/fonts/JetBrainsMono/300/italic"
        - src: "/tmp/fonts/ttf/JetBrainsMono-MediumItalic.ttf"
          dest: "/etc/rstudio/fonts/JetBrainsMono/400/italic"
        - src: "/tmp/fonts/ttf/JetBrainsMono-BoldItalic.ttf"
          dest: "/etc/rstudio/fonts/JetBrainsMono/700/italic"
