- name: Set Posit License
  when: workbench_file_license is defined
  ansible.builtin.copy:
    content: "{{ workbench_file_license }}"
    dest: "/var/lib/rstudio-server/license.lic"
    owner: "{{ workbench_server_server_user }}"
    group: "{{ workbench_server_server_user }}"
    mode: "0600"
  no_log: true
  notify: Restart rstudio-server service

- name: Create Launcher Key Pair
  community.crypto.openssl_privatekey:
    path: "/etc/rstudio/launcher.pem"
    type: RSA
    size: 4096
    mode: "0600"
  register: launcher_key

- name: Create Launcher Public Key
  community.crypto.openssl_publickey:
    privatekey_path: "/etc/rstudio/launcher.pem"
    path: "/etc/rstudio/launcher.pub"

- name: Define custom arch for mkcert
  when: workbench_create_localhost_certificate | bool
  ansible.builtin.set_fact:
    mkcert_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}"

- name: Download mkcert
  when: workbench_create_localhost_certificate | bool
  ansible.builtin.get_url:
    url: "https://dl.filippo.io/mkcert/latest?for=linux/{{ mkcert_arch }}"
    dest: "/usr/local/bin/mkcert"
    mode: "0755"

- name: Create Launcher SSL Certificate
  when: workbench_create_localhost_certificate | bool
  ansible.builtin.command:
    cmd: "/usr/local/bin/mkcert -install -cert-file /var/lib/rstudio-launcher/localhost.crt -key-file /var/lib/rstudio-launcher/localhost.key localhost"
    creates: "/var/lib/rstudio-launcher/localhost.crt"

- name: Set Launcher SSL Certificate Permissions
  when: workbench_create_localhost_certificate | bool
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ workbench_server_server_user }}"
    group: "{{ workbench_launcher_server_admin_group }}"
    mode: "0400"
  loop:
    - /var/lib/rstudio-launcher/localhost.crt
    - /var/lib/rstudio-launcher/localhost.key

- name: Create secure-cookie-key
  ansible.builtin.copy:
    content: '{{ lookup(''password'', ''/dev/null chars=ascii_letters,digits length=32 seed=ansible_facts["architecture"]'') }}'
    dest: "/var/lib/rstudio-server/secure-cookie-key"
    owner: "{{ workbench_server_server_user }}"
    group: "{{ workbench_server_server_user }}"
    mode: "0600"
  no_log: true
  notify: Restart rstudio-server service

- name: Create session-rpc-key
  ansible.builtin.copy:
    content: '{{ lookup(''password'', ''/dev/null chars=ascii_letters,digits length=32 seed=ansible_facts["machine_id"]'') }}'
    dest: "/var/lib/rstudio-server/session-rpc-key"
    owner: "{{ workbench_server_server_user }}"
    group: "{{ workbench_server_server_user }}"
    mode: "0600"
  no_log: true
  notify: Restart rstudio-server service
