- name: "[Jupyter] Gather package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "[Jupyter]  Install python3 development package"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ 'python3-dev' if ansible_facts['os_family'] == 'Debian' else 'python3-devel' }}"
    - python3-pip
  when: "item not in ansible_facts.packages"

- name: "[Jupyter] Get installed pip packages with versions"
  ansible.builtin.command: "/usr/bin/pip3 list --format=json"
  register: installed_packages
  changed_when: false

- name: "Create requirements file for Jupyter packages"
  ansible.builtin.copy:
    dest: "/tmp/jupyter_requirements.txt"
    mode: "0644"
    content: |
      jupyterlab{{ workbench_jupyter_jupyterlab_version }}
      notebook{{ workbench_jupyter_jupyternotebook_version }}
      pwb_jupyterlab{{ workbench_jupyter_jupyterlab_extension_version }}
      jupyterlab_gitlab{{ workbench_jupyter_jupyterlab_gitlab_version }}
      jupyterlab-git
      jupyterlab-code-formatter
      lckr_jupyterlab_variableinspector{{ workbench_jupyter_lckr_jupyterlab_variableinspector_version }}
      jupyter-resource-usage{{ workbench_jupyter_jupyter_resource_usage_version }}
      jupyter_scheduler{{ workbench_jupyter_jupyter_scheduler_version }}

- name: "Install Jupyter packages from requirements file"
  ansible.builtin.pip:
    requirements: "/tmp/jupyter_requirements.txt"
    executable: /usr/bin/pip3
    state: present
    break_system_packages: true
  notify: Restart rstudio-server service
