- name: "[Config] Create /etc/rstudio"
  ansible.builtin.file:
    path: /etc/rstudio
    state: directory
    mode: "0644"
    owner: root
    group: "{{ workbench_server_server_user }}"

- name: "[Config] Apply Posit Workbench configuration (/etc/rstudio)"
  ansible.builtin.template:
    src: "{{ item.file }}.j2"
    dest: "/etc/rstudio/{{ item.file }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  no_log: "{{ workbench_database_password is defined }}"
  notify: >
    {{
      [ item.restart ] +
      (workbench_database_password is defined | ternary(['Encrypt Postgresql Password'], []) )
    }}
  loop:
    - file: "database.conf"
      mode: "0600"
      restart: "Restart rstudio-server service"
    - file: "jupyter.conf"
      mode: "0644"
      restart: "Restart rstudio-server service"
    - file: "launcher.conf"
      mode: "0644"
      restart: "Restart rstudio-launcher service"
    - file: "logging.conf"
      mode: "0644"
      restart: "Restart rstudio-server service"
    - file: "notifications.conf"
      mode: "0644"
      restart: "Restart rstudio-server service"
    - file: "positron.conf"
      mode: "0644"
      restart: "Restart rstudio-server service"
    - file: "repos.conf"
      mode: "0644"
      restart: "Restart rstudio-server service"
    - file: "rstudio-prefs.json"
      mode: "0644"
      restart: "Restart rstudio-server service"
    - file: "rserver.conf"
      mode: "0644"
      restart: "Restart rstudio-server service"
    - file: "r-versions"
      mode: "0644"
      restart: "Restart rstudio-server service"
    - file: "rsession.conf"
      mode: "0644"
      restart: "Restart rstudio-server service"
    - file: "vscode.conf"
      mode: "0644"
      restart: "Restart rstudio-server service"
    - file: "vscode.extensions.conf"
      mode: "0644"
      restart: "Restart rstudio-server service"

- name: "[Config] Add static files"
  ansible.builtin.copy:
    src: "{{ item.name }}"
    dest: "/etc/rstudio/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { name: "vscode-user-settings.json", mode: "0644" }

- name: "[Config] Copy pam profile"
  ansible.builtin.template:
    src: "{{ item.name }}.j2"
    dest: "/etc/pam.d/{{ workbench_server_auth_pam_sessions_profile }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { name: "rstudio-pam", mode: "0644" }

- name: "[Config] Write openid-client-secret"
  when: workbench_server_oidc_client_id is defined and workbench_server_oidc_client_secret is defined
  ansible.builtin.template:
    src: openid-client-secret.j2
    dest: /etc/rstudio/openid-client-secret
    owner: root
    group: root
    mode: "0600"
  no_log: true
  notify:
    - Encrypt OIDC client secret
    - Restart rstudio-server service

- name: "[Config] [RedHat] Create /etc/authselect/custom/pwb for SCIM user provisioning"
  when: ansible_os_family == 'RedHat' and workbench_server_user_provisioning_enabled == 1
  ansible.builtin.command:
    cmd: authselect create-profile pwb --base-on=minimal
    creates: /etc/authselect/custom/pwb

- name: "[Config] [RedHat] Alter nsswitch.conf for SCIM user provisioning"
  when: ansible_os_family == 'RedHat' and workbench_server_user_provisioning_enabled == 1
  ansible.builtin.lineinfile:
    path: /etc/authselect/custom/pwb/nsswitch.conf
    regexp: "{{ item.search }}"
    line: "{{ item.replace }}"
  loop:
    - {
        search: 'passwd:     files {if "with-altfiles":altfiles }systemd',
        replace: 'passwd:     pwb files {if "with-altfiles":altfiles }systemd {exclude if "with-custom-passwd"}',
      }
    - {
        search: "shadow:     files",
        replace: 'shadow:     pwb files                                       {exclude if "with-custom-shadow"}',
      }
    - {
        search: 'group:      files {if "with-altfiles":altfiles }systemd',
        replace: 'group:      files {if "with-altfiles":altfiles }systemd pwb {exclude if "with-custom-group"}',
      }

- name: "[Config] [RedHat] Enable custom nss profile"
  when: ansible_os_family == 'RedHat' and workbench_server_user_provisioning_enabled == 1
  ansible.builtin.command: authselect select --force custom/pwb with-mkhomedir

- name: "[Config] [RedHat] Ensure oddjob-mkhomedir is installed"
  when: ansible_os_family == 'RedHat' and workbench_server_user_provisioning_enabled == 1
  ansible.builtin.dnf:
    name: oddjob-mkhomedir
    state: present

- name: "[Config] [RedHat] Enable oddjob systemd for SCIM user provisioning"
  when: ansible_os_family == 'RedHat' and workbench_server_user_provisioning_enabled == 1
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: oddjobd
