# tasks file for workbench

- name: Import 01_syslibs.yaml
  ansible.builtin.import_tasks: 01_syslibs.yaml

# Install from Artifactory when enabled
- name: Include 02a_install_posit_artifactory.yaml
  when: workbench_artifactory_enabled | bool
  ansible.builtin.include_tasks: 02a_install_posit_artifactory.yaml

# Install from default sources when Artifactory is disabled
- name: Include 02a_install_posit_default.yaml
  when: not workbench_artifactory_enabled | bool
  ansible.builtin.include_tasks: 02a_install_posit_default.yaml

- name: Import 04_fonts.yaml
  ansible.builtin.import_tasks: 04_fonts.yaml

- name: Import 05_secrets.yaml
  ansible.builtin.import_tasks: 05_secrets.yaml

- name: Import 06_startup.yaml
  ansible.builtin.import_tasks: 06_startup.yaml

- name: Import 07_jupyter.yaml
  ansible.builtin.import_tasks: 07_jupyter.yaml

- name: Import 08_config.yaml
  ansible.builtin.import_tasks: 08_config.yaml

- name: Import 09_user_env.yaml
  ansible.builtin.import_tasks: 09_user_env.yaml

- name: Include 10_selinux.yaml
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['selinux']['status'] == 'enabled'
  ansible.builtin.include_tasks: 10_selinux.yaml
