- name: "'Update mode': Query latest python release for respective minor versions from conda"
  block:
    - name: "'Update mode': Get latest available Python versions using conda search"
      ansible.builtin.command: "/opt/python/miniconda/bin/conda search --json python={{ item }}"
      register: conda_search_results
      loop: "{{ python_python_versions }}"
      changed_when: false

    - name: "'Update mode': Store latest Python version for each Python version in a dictionary"
      set_fact:
        latest_python_versions: "{{ latest_python_versions | default({}) | combine({item.item:     (item.stdout | from_json)['python'] | map(attribute='version') | list | community.general.version_sort | last}) }}"
      loop: "{{ conda_search_results.results }}"
      # output is too verbose
      no_log: true

    - name: "'Update mode': Print latest available Python conda versions"
      debug:
        var: latest_python_versions

- name: "'Update mode': Compare dictionary and list and keep keys of non-matching rows"
  set_fact:
    python_python_versions: "{{ latest_python_versions | dict2items | rejectattr('value', 'in', python_version_list) | map(attribute='key') | list }}"
