### Database (database.conf)
# https://docs.posit.co/ide/server-pro/database/configuration.html
workbench_database_provider: sqlite
workbench_database_directory: /var/lib/rstudio-server
workbench_database_host: localhost
workbench_database_database: workbenchdb
workbench_database_username: workbench_db_user
workbench_database_password: workbench_db_password
workbench_database_port: 5432
workbench_database_connection_timeout_seconds: 10
workbench_database_connection_uri: ""
