---
# defaults file for workbench

workbench_version: "2024.04.3-776.pro2"
workbench_server_user: rstudio-server

workbench_create_local_test_user: false
workbench_local_test_user_name: posit
workbench_local_test_user_password: posit
