### Server (rserver.conf)
# https://docs.posit.co/ide/server-pro/reference/rserver_conf.html

workbench_server_server_user: rstudio-server
workbench_server_server_data_dir: /var/run/rstudio-server
workbench_server_server_access_log: 0
workbench_server_server_license_type: local
workbench_server_server_license_warning_days: 15
workbench_server_server_project_sharing: 1
workbench_server_server_admin_enabled: 1
workbench_server_server_load_balancing_enabled: 0

workbench_server_launcher_address: localhost
workbench_server_launcher_port: 5559
workbench_server_launcher_session_callback_address: http://localhost:8787
workbench_server_launcher_default_cluster: Local
workbench_server_launcher_use_ssl: 1
workbench_server_launcher_sessions_enabled: 1
workbench_server_launcher_verify_ssl_certs: 1
workbench_server_launcher_session_callback_verify_ssl_certs: 1

workbench_server_www_thread_pool_size: 2
workbench_server_www_enable_origin_check: 0
workbench_server_www_ssl_enabled: 0
workbench_server_www_session_ssl_enabled: 1

workbench_server_rsession_no_profile: 0
workbench_server_rsession_diagnostics_enabled: 0
workbench_server_rsession_diagnostics_strace_enabled: 0

workbench_server_db_connection_timeout: 15

workbench_server_auth_timeout_minutes: 5040
workbench_server_auth_pam_require_password_prompt: 1
workbench_server_auth_pam_sessions_enabled: 1
workbench_server_auth_cookies_force_secure: 0
workbench_server_auth_openid: 0
workbench_server_auth_openid_username_claim: preferred_username
workbench_server_auth_saml: 0
workbench_server_auth_pam_sessions_profile: su
workbench_server_auth_pam_sessions_use_password: 0
workbench_server_auth_pam_sessions_close: 0

workbench_server_monitor_interval_seconds: 60
workbench_server_monitor_stderr_enabled: 0
workbench_server_monitor_data_path: /var/lib/rstudio-server/monitor
workbench_server_monitor_rstudio_session_metrics: 1
workbench_server_monitor_audit_data_path: /var/lib/rstudio-server/audit
workbench_server_monitor_audit_r_console: none
workbench_server_monitor_shared_storage_path: /var/lib/rstudio-server/shared-storage

workbench_metrics_enabled: 0
workbench_metrics_port: 8989

workbench_server_databricks_enabled: auto

workbench_server_user_provisioning_enabled: 0
workbench_server_user_homedir_path: /home
workbench_server_user_provisioning_start_uid: 15000
