### Session (session.conf)
# https://docs.posit.co/ide/server-pro/reference/rsession_conf.html
workbench_session_session_connections_block_suspend: 0
workbench_session_session_external_pointers_block_suspend: 0
workbench_session_session_timeout_minutes: 300
workbench_session_session_timeout_suspend: 1
workbench_session_session_save_action_default: no
workbench_session_session_quit_child_processes_on_exit: 1
workbench_session_restrict_directory_view: 1
workbench_session_allow_r_cran_repos_edit: 0
workbench_session_copilot_enabled: 1
workbench_session_session_timeout_kill_hours: 24
