### VSCode (vscode.conf)
# https://docs.posit.co/ide/server-pro/vscode_sessions/configuration.html

workbench_vscode_enabled: 1
workbench_vscode_exe: /usr/lib/rstudio-server/bin/code-server/bin/code-server
workbench_vscode_args: --host=0.0.0.0

# additional_vscode_extensions:
# - extension.1
# - extension.2
