# removes all R versions that are not in the r_versions list
r_remove_old_r_versions: true

r_r_versions:
  - 4.0.5
  - 4.1.3
  - 4.2.3
  - 4.3.3
### Optional vars
# r_r_custom_repos:
# r_additional_options:
