when:
  event: [push, cron, manual]

matrix:
  SCENARIO:
    - workbench_default

steps:
  - name: "Test devxy.posit.workbench"
    image: library/docker:27.3.1-dind-alpine3.20
    privileged: true
    environment:
      # force output of ANSI colors
      PY_COLORS: 1
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: "/dind-certs/client"
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - ci-tmp-rwx:/dind-certs
    commands:
      - apk add -q --no-cache python3 python3-dev py3-pip gcc git curl build-base autoconf automake py3-cryptography linux-headers musl-dev libffi-dev openssl-dev openssh yaml-dev
      - python3 --version
      - python3 -m venv ~/venv/ansible-molecule
      - source ~/venv/ansible-molecule/bin/activate
      - python3 -m pip install -q 'ansible-core<2.17' molecule-plugins[docker] cryptography
      - ansible --version
      - molecule --version
      - cd extensions
      - molecule test --scenario-name ${SCENARIO}
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 300Mi
            cpu: 500m
          limits:
            memory: 1000Mi
            cpu: 4000m
        tolerations:
          - key: "CI"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
        nodeSelector:
          kubernetes.io/arch: amd64
          node.kubernetes.io/instance-type: AX42

  - name: "ntfy"
    image: codeberg.org/l-x/woodpecker-ntfy:1.3.1
    when:
      - status: [failure]
    settings:
      url: https://ntfy.devxy.io/ci-builds
      token:
        from_secret: ntfy_token
      title: "CI '${CI_REPO}' failed"
      actions: view, Open build, ${CI_PIPELINE_URL}, clear=false;
      click: ${CI_BUILD_LINK}
      message: |
        Workflow: ${CI_WORKFLOW_NAME/\n//}
        Commit message: ${CI_COMMIT_MESSAGE/\n//}
        Commit Author: ${CI_COMMIT_AUTHOR/\n//}
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 100Mi
            cpu: 0m
          limits:
            memory: 300Mi
            cpu: 200m

services:
  docker:
    image: docker:27-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /dind-certs
    volumes:
      - ci-tmp-rwx:/dind-certs
    ports:
      - 2376
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 600Mi
            cpu: 500m
          limits:
            memory: 1000Mi
            cpu: 4000m
        tolerations:
          - key: "CI"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
        nodeSelector:
          kubernetes.io/arch: amd64
          node.kubernetes.io/instance-type: AX42
